function StereoInfo = cameraParamsFormatConvertFromMatlabCV
% cameraParamsFormatConvertFromMatlabCV: Converts MATLAB Computer Vision Toolbox
% stereo camera parameters to a custom StereoInfo structure.
%
%   StereoInfo = cameraParamsFormatConvertFromMatlabCV
%
%   This function expects a 'stereoParams' object, typically generated by
%   MATLAB's Stereo Camera Calibrator app or 'estimateStereoParameters'
%   function, to be present in the caller's workspace.
%
%   Output:
%     StereoInfo - A structure containing formatted stereo camera
%                  calibration information.

% Check if 'stereoParams' variable exists in the caller's workspace
if ~evalin('caller', 'exist(''stereoParams'', ''var'')')
    error('StereoParams:NotFound', 'The variable ''stereoParams'' was not found in the caller''s workspace. Please ensure you have loaded or generated your stereo camera parameters and it is named ''stereoParams''.');
end

% Check if 'stereoParams' is a struct or an object with expected fields
% This is a basic check; more robust validation could be added if needed.
if ~evalin('caller', 'isstruct(stereoParams) || isobject(stereoParams)')
    error('StereoParams:InvalidType', 'The variable ''stereoParams'' is not a valid structure or object type.');
end

% Retrieve the stereoParams object from the caller's workspace
stereoParams = evalin('caller', 'stereoParams');

% Initialize StereoInfo fields to ensure they always exist
StereoInfo.cameraParams.cameraParamsLeft = [];
StereoInfo.cameraParams.cameraParamsRight = [];
StereoInfo.cameraParams.rotationMatrix = [];
StereoInfo.cameraParams.translationVector = [];
StereoInfo.cameraParams.FundamentalMatrix = [];
StereoInfo.cameraParams.EssentialMatrix = [];

% Assign values, adding checks for field existence for robustness
if isprop(stereoParams, 'CameraParameters1')
    StereoInfo.cameraParams.cameraParamsLeft = stereoParams.CameraParameters1;
else
    warning('StereoParams:MissingField', 'stereoParams.CameraParameters1 not found. This field will be empty.');
end

if isprop(stereoParams, 'CameraParameters2')
    StereoInfo.cameraParams.cameraParamsRight = stereoParams.CameraParameters2;
else
    warning('StereoParams:MissingField', 'stereoParams.CameraParameters2 not found. This field will be empty.');
end

if isprop(stereoParams, 'PoseCamera2') 
        StereoInfo.cameraParams.rotationMatrix = stereoParams.PoseCamera2.R;
        StereoInfo.cameraParams.translationVector = stereoParams.PoseCamera2.Translation;
else
    warning('StereoParams:MissingField', 'stereoParams.PoseCamera2 (or its subfields R/Translation) not found. Pose information will be empty.');
end

if isprop(stereoParams, 'FundamentalMatrix')
    StereoInfo.cameraParams.FundamentalMatrix = stereoParams.FundamentalMatrix;
else
    warning('StereoParams:MissingField', 'stereoParams.FundamentalMatrix not found. This field will be empty.');
end

if isprop(stereoParams, 'EssentialMatrix')
    StereoInfo.cameraParams.EssentialMatrix = stereoParams.EssentialMatrix;
else
    warning('StereoParams:MissingField', 'stereoParams.EssentialMatrix not found. This field will be empty.');
end

end